### ISSUE TITLE
deploy 之后是否可以刷新七牛cdn的缓存吗？

### ISSUE THREAD

**Issue by YahuiWong** [rise0chen/hexo-deployer-qiniucloud#1]
每次打开站点页面的时候发现还是旧的首页或者其它页面。

**Comment by rise0chen** [comment]
有两种缓存，CDN缓存和浏览器缓存。
一、CDN缓存。
七牛--融合CDN--缓存配置--缓存配置--自定义--全局配置--缓存时间 设置成0秒。
二、浏览器缓存
  1、七牛--对象储存--空间设置--文件客户端缓存 maxAge 建议设置成43200秒即一天。
  2、刷新浏览器 或 清除浏览器缓存。

**Comment by YahuiWong** [comment]
@rise0chen 感谢
